fragment dataConnectorConfigFragment on DebeziumConnectorConfigType {
    id,
    connectorClass,
    tasksMax,
    databaseHostname,
    databasePort,
    databaseUser,
    databasePassword,
    databaseServerId,
    databaseServerName,
    databaseWhitelist,
    databaseHistoryKafkaBootstrapServers,
    databaseHistoryKafkaTopic
}
