#import "../fragments/dataConnectorConfigFragment.gql"

query dataConnectors {
    dataConnectors: allDebeziumConnectors {
        id,
        name,
        config {
            ...dataConnectorConfigFragment
        }
    }
}
