query dataConnectors {
    dataConnectors: allDataConnectors {
        id,
        label,
        config,
        dataConnectorType {
            id,
            label,
            config
        }
    }
}
