query project($id: IntID!) {
    project(id: $id) {
        id,
        label,
        pipelines {
            id,
            label
        },
        dashboards {
            id,
            label
        }
    }
}
