query project($id: IntID!) {
    project(id: $id) {
        id,
        label,
        dataConnectors {
            id,
            label,
            config,
            dataConnectorType {
                id,
                label,
                config
            }
        }
        pipelines {
            id,
            label
        },
        dashboards {
            id,
            label
        }
    }
}
